version: '3.4'
services:
  share-site-creators-share:
    image: alfresco-share-share-site-creators:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../share-site-creators-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: share-site-creators-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  share-site-creators-acs:
    image: alfresco-content-services-share-site-creators:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../share-site-creators-platform-docker/target
      network: host
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      OVERRIDE_JAVA_OPTS: ""
      JAVA_OPTS: "
        -Dsolr.alfresco.port.ssl=8983
        $$OVERRIDE_JAVA_OPTS
      "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - share-site-creators-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - share-site-creators-postgres
  share-site-creators-postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - share-site-creators-db-volume:/var/lib/postgresql/data
  share-site-creators-ass:
    image: ${docker.ass.image}:${alfresco.ass.version}
    environment:
      SOLR_ALFRESCO_HOST: share-site-creators-acs
      SOLR_ALFRESCO_PORT: 8983
      SOLR_SOLR_HOST: share-site-creators-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: https
    ports:
      - "8983:8983"
    volumes:
      - share-site-creators-ass-volume:/opt/alfresco-search-services/contentstore
      - share-site-creators-ass-volume:/opt/alfresco-search-services/data

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.5.7
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      ACTIVEMQ_USER: "admin"
      ACTIVEMQ_PASSWORD: "admin"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8090:8090"
    links:
      - activemq

  transform-router:
    image: docker-alfresco-mirror.priv.atolcd.com/alfresco/alfresco-transform-router:1.5.2
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL : "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8095:8095
    links:
      - activemq

  shared-file-store:
    image: docker-alfresco-mirror.priv.atolcd.com/alfresco/alfresco-shared-file-store:0.16.1
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - 8099:8099
    volumes:
      - sfs-data:/tmp/Alfresco/sfs

#  transform-dte-engine:
#    image: docker-alfresco-mirror.priv.atolcd.com/alfresco/transform-dte-engine:1.2.0
#    environment:
#      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80 -DdteServerUrl=http://alfresco-dte.dvt.cloud.priv.atolcd.com:8080/transformation-backend"
#      ACTIVEMQ_URL: "nio://activemq:61616"
#      ACTIVEMQ_USER: "admin"
#      ACTIVEMQ_PASSWORD: "admin"
#      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
#    ports:
#      - 8091:8090
#    links:
#      - activemq
  activemq:
    image: ${docker.activemq.image}:${activemq.version}
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

volumes:
  share-site-creators-acs-volume:
    external: true
  share-site-creators-db-volume:
    external: true
  share-site-creators-ass-volume:
    external: true
  sfs-data:
    driver_opts:
      type: tmpfs
      device: tmpfs